# Generated by Django 3.2.9 on 2021-12-09 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_title', models.CharField(help_text='Enter name of Artifact', max_length=25)),
                ('artifact_summary', models.CharField(help_text='Enter description of Artifact', max_length=250)),
                ('inheritance_date', models.DateField(help_text='Enter committment of artifact date')),
                ('contributor_name', models.CharField(help_text='Enter your name', max_length=50)),
                ('artifact_image', models.TextField()),
                ('access_key', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artifact',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'myapp_image',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inheritance.artifact')),
            ],
            options={
                'db_table': 'contributor',
            },
        ),
        migrations.CreateModel(
            name='Artifact_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inheritance.artifact')),
            ],
            options={
                'db_table': 'artifact_instance',
            },
        ),
    ]
