# Generated by Django 4.0 on 2021-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('artifact_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_link', models.URLField()),
                ('title', models.CharField(max_length=13)),
                ('description', models.TextField(max_length=444)),
            ],
        ),
    ]
