# Generated by Django 4.0 on 2021-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='title',
        ),
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(default='images/Sound.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='imgdesc',
            field=models.CharField(default='loremipsumcoast', max_length=44),
        ),
        migrations.AddField(
            model_name='artifact',
            name='imgtitle',
            field=models.CharField(default='Good Code', max_length=13),
        ),
    ]
