# Generated by Django 3.2.9 on 2021-12-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0002_remove_artifact_description_remove_artifact_img_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='imgdesc',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='imgtitle',
            field=models.CharField(max_length=13),
        ),
    ]
