# Generated by Django 3.2.9 on 2021-12-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0004_auto_20211229_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['-created_at']},
        ),
    ]
