# Generated by Django 4.0 on 2021-12-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0003_alter_artifact_image_alter_artifact_imgdesc_and_more'),
        ('inheritanceapp', '0005_alter_artifact_options'),
    ]

    operations = [
    ]
