# Generated by Django 4.0 on 2021-12-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0006_merge_20211229_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='imgdesc',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='imgtitle',
            field=models.CharField(max_length=11),
        ),
    ]
