# Generated by Django 4.0 on 2021-12-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0007_alter_artifact_imgdesc_alter_artifact_imgtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BINARY', 'binary'), ('INVERT', 'invert')], default='NO_FILTER', max_length=50),
        ),
    ]
