# Generated by Django 4.0 on 2021-12-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0008_artifact_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='action',
        ),
    ]
