# Generated by Django 4.0 on 2022-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0009_remove_artifact_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='imgfilter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
