# Generated by Django 4.0 on 2022-01-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0011_alter_artifact_imgfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.CharField(default='artistic', max_length=25),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='imgfilter',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
