# Generated by Django 4.0 on 2022-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0013_alter_artifact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='category',
            field=models.CharField(choices=[('', ''), ('artistic', 'artistic'), ('beautiful', 'beautiful'), ('profound', 'profound')], default='', max_length=25),
        ),
    ]
