# Generated by Django 4.0 on 2022-01-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0015_deleteartifact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteArtifact',
        ),
    ]
