# Generated by Django 4.0 on 2022-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritanceapp', '0016_delete_deleteartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='category',
            field=models.CharField(choices=[('', ''), ('artistic', 'artistic'), ('beautiful', 'beautiful'), ('melancholy', 'melancholy'), ('profound', 'profound')], default='', max_length=25),
        ),
    ]
